// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO Users(id,username,firstname,lastname,email,password_hash,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Firstname    string
	Lastname     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}
