// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_locus_view.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createView = `-- name: CreateView :one
INSERT INTO locus_views (
    user_id,
    locus_id,
    viewed_at
) VALUES (
    $1, $2, NOW() -- Use NOW() here so you don't have to pass it from Go
)
ON CONFLICT (user_id, locus_id) DO NOTHING
RETURNING user_id, locus_id, viewed_at
`

type CreateViewParams struct {
	UserID  uuid.UUID
	LocusID uuid.UUID
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (LocusView, error) {
	row := q.db.QueryRow(ctx, createView, arg.UserID, arg.LocusID)
	var i LocusView
	err := row.Scan(&i.UserID, &i.LocusID, &i.ViewedAt)
	return i, err
}
