// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_loci.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLoci = `-- name: CreateLoci :many
INSERT INTO loci(
    user_id,
    message,
    location )
VALUES
    ($1,$2,$3) 
RETURNING id, user_id, message, location, created_at, view_count, replies_count, visibility_score
`

type CreateLociParams struct {
	UserID   uuid.UUID
	Message  string
	Location interface{}
}

func (q *Queries) CreateLoci(ctx context.Context, arg CreateLociParams) ([]Loci, error) {
	rows, err := q.db.Query(ctx, createLoci, arg.UserID, arg.Message, arg.Location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loci
	for rows.Next() {
		var i Loci
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.Location,
			&i.CreatedAt,
			&i.ViewCount,
			&i.RepliesCount,
			&i.VisibilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
