// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_loci.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLoci = `-- name: CreateLoci :many
INSERT INTO loci(
    id,
    user_id,
    message,
    location )
VALUES
    ($1,$2,$3,
    ST_MakePoint($4, $5)::geography) 
RETURNING
    id, 
    user_id, 
    message, 
    ST_AsText(location) AS location, -- This converts binary geography to string
    created_at, 
    view_count, 
    replies_count, 
    visibility_score
`

type CreateLociParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Message       string
	StMakepoint   interface{}
	StMakepoint_2 interface{}
}

type CreateLociRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Message         string
	Location        interface{}
	CreatedAt       time.Time
	ViewCount       int32
	RepliesCount    int32
	VisibilityScore float64
}

func (q *Queries) CreateLoci(ctx context.Context, arg CreateLociParams) ([]CreateLociRow, error) {
	rows, err := q.db.Query(ctx, createLoci,
		arg.ID,
		arg.UserID,
		arg.Message,
		arg.StMakepoint,
		arg.StMakepoint_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateLociRow
	for rows.Next() {
		var i CreateLociRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.Location,
			&i.CreatedAt,
			&i.ViewCount,
			&i.RepliesCount,
			&i.VisibilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
