// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_loci.sql

package sqlc

import (
	"context"
)

const getLociInBounds = `-- name: GetLociInBounds :many
SELECT
    id,
    user_id,
    message,
    location,
    created_at,
    view_count,
    replies_count,
    visibility_score
FROM
    loci
WHERE
    ST_Within(location::geometry, ST_MakeEnvelope($1,$2,$3,$4, 4326))
    AND visibility_score >= 0.0
ORDER BY created_at DESC
`

type GetLociInBoundsParams struct {
	StMakeenvelope   interface{}
	StMakeenvelope_2 interface{}
	StMakeenvelope_3 interface{}
	StMakeenvelope_4 interface{}
}

func (q *Queries) GetLociInBounds(ctx context.Context, arg GetLociInBoundsParams) ([]Loci, error) {
	rows, err := q.db.Query(ctx, getLociInBounds,
		arg.StMakeenvelope,
		arg.StMakeenvelope_2,
		arg.StMakeenvelope_3,
		arg.StMakeenvelope_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loci
	for rows.Next() {
		var i Loci
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.Location,
			&i.CreatedAt,
			&i.ViewCount,
			&i.RepliesCount,
			&i.VisibilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
