// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_loci.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLociInBounds = `-- name: GetLociInBounds :many
SELECT
    id,
    user_id,
    message
    location,
    created_at,
    view_count,
    replies_count,
    visibility_score
FROM
    loci
WHERE
    ST_Within(location::geometry, ST_MakeEnvelope($1,$2,$3,$4,$5, 4326))
    AND visibility_score > 0.1
ORDER BY created_at DESC
`

type GetLociInBoundsParams struct {
	StMakeenvelope   interface{}
	StMakeenvelope_2 interface{}
	StMakeenvelope_3 interface{}
	StMakeenvelope_4 interface{}
	StMakeenvelope_5 interface{}
}

type GetLociInBoundsRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Location        string
	CreatedAt       time.Time
	ViewCount       int32
	RepliesCount    int32
	VisibilityScore float64
}

func (q *Queries) GetLociInBounds(ctx context.Context, arg GetLociInBoundsParams) ([]GetLociInBoundsRow, error) {
	rows, err := q.db.Query(ctx, getLociInBounds,
		arg.StMakeenvelope,
		arg.StMakeenvelope_2,
		arg.StMakeenvelope_3,
		arg.StMakeenvelope_4,
		arg.StMakeenvelope_5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLociInBoundsRow
	for rows.Next() {
		var i GetLociInBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Location,
			&i.CreatedAt,
			&i.ViewCount,
			&i.RepliesCount,
			&i.VisibilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
