// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_reply.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReplyForBroadcast = `-- name: GetReplyForBroadcast :one
SELECT r.id, r.content, r.created_at, u.username, ST_Y(l.location::geometry)::float8 as lat, ST_X(l.location::geometry)::float8 as long
FROM replies r
JOIN users u ON r.user_id = u.id
JOIN loci l ON r.locus_id = l.id
WHERE r.id = $1
`

type GetReplyForBroadcastRow struct {
	ID        uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	Username  string
	Lat       float64
	Long      float64
}

func (q *Queries) GetReplyForBroadcast(ctx context.Context, id uuid.UUID) (GetReplyForBroadcastRow, error) {
	row := q.db.QueryRow(ctx, getReplyForBroadcast, id)
	var i GetReplyForBroadcastRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.Username,
		&i.Lat,
		&i.Long,
	)
	return i, err
}
