// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_loci.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLociInBounds = `-- name: GetLociInBounds :many
SELECT
    id,
    user_id,
    message,
    ST_Y(location::geometry)::float8 as lat,
    ST_X(location::geometry)::float8 as long,
    created_at,
    view_count,
    replies_count,
    visibility_score
FROM
    loci
WHERE
    ST_Within(location::geometry, ST_MakeEnvelope($1,$2,$3,$4, 4326))
    AND visibility_score >= 0.0
ORDER BY created_at DESC
`

type GetLociInBoundsParams struct {
	StMakeenvelope   interface{}
	StMakeenvelope_2 interface{}
	StMakeenvelope_3 interface{}
	StMakeenvelope_4 interface{}
}

type GetLociInBoundsRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Message         string
	Lat             float64
	Long            float64
	CreatedAt       time.Time
	ViewCount       int32
	RepliesCount    int32
	VisibilityScore float64
}

func (q *Queries) GetLociInBounds(ctx context.Context, arg GetLociInBoundsParams) ([]GetLociInBoundsRow, error) {
	rows, err := q.db.Query(ctx, getLociInBounds,
		arg.StMakeenvelope,
		arg.StMakeenvelope_2,
		arg.StMakeenvelope_3,
		arg.StMakeenvelope_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLociInBoundsRow
	for rows.Next() {
		var i GetLociInBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.Lat,
			&i.Long,
			&i.CreatedAt,
			&i.ViewCount,
			&i.RepliesCount,
			&i.VisibilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocusLocation = `-- name: GetLocusLocation :one
SELECT id, ST_Y(location::geometry)::float8 as lat, ST_X(location::geometry)::float8 as long
FROM loci
WHERE id = $1
`

type GetLocusLocationRow struct {
	ID   uuid.UUID
	Lat  float64
	Long float64
}

func (q *Queries) GetLocusLocation(ctx context.Context, id uuid.UUID) (GetLocusLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocusLocation, id)
	var i GetLocusLocationRow
	err := row.Scan(&i.ID, &i.Lat, &i.Long)
	return i, err
}
