// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loci_view_cont.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE loci 
SET view_count = view_count + 1 
WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}
