// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Loci struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Message         string
	Location        interface{}
	CreatedAt       time.Time
	ViewCount       int32
	RepliesCount    int32
	VisibilityScore float64
}

type LocusView struct {
	UserID   uuid.UUID
	LocusID  uuid.UUID
	ViewedAt pgtype.Timestamp
}

type Reply struct {
	ID        uuid.UUID
	LocusID   uuid.UUID
	UserID    uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	Firstname    string
	Lastname     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
