// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Loci struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Message   string
	Location  interface{}
	CreatedAt time.Time
	ViewCount int32
}

type User struct {
	ID           uuid.UUID
	Username     string
	Firstname    string
	Lastname     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
