// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReply = `-- name: CreateReply :one
INSERT INTO replies (locus_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, locus_id, user_id, content, created_at
`

type CreateReplyParams struct {
	LocusID uuid.UUID
	UserID  uuid.UUID
	Content string
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (Reply, error) {
	row := q.db.QueryRow(ctx, createReply, arg.LocusID, arg.UserID, arg.Content)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.LocusID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getRepliesByLocus = `-- name: GetRepliesByLocus :many
SELECT 
	r.id,
	r.locus_id,
	r.user_id,
	r.content,
	r.created_at
FROM replies r
WHERE r.locus_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) GetRepliesByLocus(ctx context.Context, locusID uuid.UUID) ([]Reply, error) {
	rows, err := q.db.Query(ctx, getRepliesByLocus, locusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reply
	for rows.Next() {
		var i Reply
		if err := rows.Scan(
			&i.ID,
			&i.LocusID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementReplyCount = `-- name: IncrementReplyCount :exec
UPDATE loci 
SET replies_count = replies_count + 1
WHERE id = $1
`

func (q *Queries) IncrementReplyCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReplyCount, id)
	return err
}
