// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_login.sql

package sqlc

import (
	"context"
)

const login = `-- name: Login :one
SELECT id,username,firstname,lastname,email,password_hash,created_at FROM Users WHERE email=$1
`

func (q *Queries) Login(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, login, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
