// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_login.sql

package sqlc

import (
	"context"
)

const login = `-- name: Login :one
SELECT id,username,firstname,lastname,email,password_hash,created_at FROM Users WHERE email=$1 OR username=$2
`

type LoginParams struct {
	Email    string
	Username string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRow(ctx, login, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
