version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loci_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:   